### ISSUE TITLE
how to train the OCR ? 

### ISSUE THREAD

**Issue by Khaderoid** [rmtheis/android-ocr#24]
Hi 

i'm trying to create an app that read the water meter number like the photo shown below
![gsd8_foto1](https://cloud.githubusercontent.com/assets/10280633/6592142/41fe50f8-c7d2-11e4-9d76-ae9e1be2a4ca.gif)

my big problem is how to train OCR ?
and how to use it with tess-two ?
could you help me please?

**Comment by rmtheis** [comment]
https://code.google.com/p/tesseract-ocr/wiki/TrainingTesseract3
