### ISSUE TITLE
Recognize only numbers

### ISSUE THREAD

**Issue by ajinkyapote1** [rmtheis/android-ocr#29]
Hi,

How can i train the tess-two to recgnize only numbers?

Thanks in advance.

**Comment by rmtheis** [comment]
You don't need to re-train. Set the whitelist to "0123456789".

**Comment by ajinkyapote1** [comment]
Thanks,

I set the both the "VAR_CHAR_WHITELIST" and "VAR_CHAR_BLACKLIST" to "0123456789", but it is still scanning the letters. 
Please Help me.

**Comment by rmtheis** [comment]
Don't set a value for the blacklist.

**Comment by ajinkyapote1** [comment]
Even if i am setting only "VAR_CHAR_BLACKLIST" to "0123456789", it is scanning the numbers.
Please help me to scan numbers only.

**Comment by rmtheis** [comment]
Take a look at how it's being set in this project. [1] Note that the setVariable() call comes before setImage() is called. If you still have questions, ask a question on StackOverflow and include the code you're using.

[1] https://github.com/rmtheis/android-ocr/blob/927c2e9b2adcf8515515fd4a54ebd23123ea664b/android/src/edu/sfsu/cs/orange/ocr/CaptureActivity.java#L396
