### ISSUE TITLE
Error Exceuting in android studio libpngt.so problem

### ISSUE THREAD

**Issue by Sagaragrawal** [rmtheis/android-ocr#30]
When I am trying to execute the code in android studio to an external device i always get a error on liblept.so

LOGCAT:

10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.spnv.newapp-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "liblept.so"
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:366)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:989)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:44)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at com.spnv.newapp.CaptureActivity.initOcrEngine(CaptureActivity.java:710)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at com.spnv.newapp.CaptureActivity.onResume(CaptureActivity.java:367)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at android.app.Activity.performResume(Activity.java:6106)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3015)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3057)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2396)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:151)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5349)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
10-04 11:44:43.749 1207-1207/com.spnv.newapp E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by rmtheis** [comment]
It can't find your *.so libraries that you compiled with ndk-build. Did you run the tess-two build instructions?
