### ISSUE TITLE
OCR Detection always in landscape

### ISSUE THREAD

**Issue by pauljie018** [rmtheis/android-ocr#33]
Good Evening , I really want to thank you for making this experimental app, the issue that I am facing this time is that I already made the app orientation and camera view to portrait but the problem is the detection box is always detecting texts by landscape orientation. any help?
![12169453_1024796244217474_1455045895_o](https://cloud.githubusercontent.com/assets/12913177/10482108/2f1f9ca4-72a8-11e5-80a4-9542b5a20622.jpg)

**Comment by Frequencies** [comment]
http://stackoverflow.com/questions/16252791/zxing-camera-in-portrait-mode-on-android/16252917#16252917
Try this

**Comment by pauljie018** [comment]
Thanks really Helped me :smiley:
