### ISSUE TITLE
Problem debugging on 4.4.2 devices

### ISSUE THREAD

**Issue by pauljie018** [rmtheis/android-ocr#34]
One thing that I noticed that this app is not working on devices with Kitkat OS like (4.4.2)
Got this error:

11-12 12:41:48.601 5702-5702/com.example.fpaul.imacon_ocr W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/com.example.fpaul.imacon_ocr/files/mounted
11-12 12:41:48.766 5702-5702/com.example.fpaul.imacon_ocr D/dalvikvm: Trying to load lib /data/app-lib/com.example.fpaul.imacon_ocr-2/libpng.so 0x425286e0
11-12 12:41:48.766 5702-5702/com.example.fpaul.imacon_ocr D/dalvikvm: Added shared lib /data/app-lib/com.example.fpaul.imacon_ocr-2/libpng.so 0x425286e0
11-12 12:41:48.766 5702-5702/com.example.fpaul.imacon_ocr D/dalvikvm: No JNI_OnLoad found in /data/app-lib/com.example.fpaul.imacon_ocr-2/libpng.so 0x425286e0, skipping init
11-12 12:41:48.766 5702-5702/com.example.fpaul.imacon_ocr D/dalvikvm: Trying to load lib /data/app-lib/com.example.fpaul.imacon_ocr-2/liblept.so 0x425286e0
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/dalvikvm: dlopen("/data/app-lib/com.example.fpaul.imacon_ocr-2/liblept.so") failed: dlopen failed: cannot locate symbol "png_set_longjmp_fn" referenced by "liblept.so"...
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr W/dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/googlecode/tesseract/android/TessBaseAPI;
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr D/AndroidRuntime: Shutting down VM
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41c97c08)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime: FATAL EXCEPTION: main
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime: Process: com.example.fpaul.imacon_ocr, PID: 5702
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "png_set_longjmp_fn" referenced by "liblept.so"...
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:365)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:526)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:44)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at com.example.fpaul.imacon_ocr.CaptureActivity.initOcrEngine(CaptureActivity.java:844)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at com.example.fpaul.imacon_ocr.CaptureActivity.onResume(CaptureActivity.java:490)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1198)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at android.app.Activity.performResume(Activity.java:5532)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3066)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3105)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:175)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:146)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5602)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
11-12 12:41:48.771 5702-5702/com.example.fpaul.imacon_ocr E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

Debugging on different devices is fine like on 4.0,4.1,4.2,4.3,5.0,5.1 but on 4.4.x it force closes
DO i need to update my library or there is a serious problem ....

**Comment by rmtheis** [comment]
Yes, you need to update your library and run `ndk-build` again. See rmtheis/tess-two#106.

**Comment by pauljie018** [comment]
Thanks I'll try it
