### ISSUE TITLE
Conversion of screenshot to text is not proper

### ISSUE THREAD

**Issue by SaranyaSampath** [rmtheis/android-ocr#35]
Trying to convert android screenshot to text by using this library. But conversion is not proper. getting some text as a w , / E " . Can we convert screenshot to text by using this library or it's only applicable to  scanned images , documents. Please clarify. Or am i doing any mistake.

**Comment by rmtheis** [comment]
You're likely not making a mistake, no. You'd generally need to pre-process your input images using external tools in order to get the results you're looking for.

**Comment by SaranyaSampath** [comment]
what kind of preprocessing we need to do ?
