### ISSUE TITLE
Android New Camera2 API 

### ISSUE THREAD

**Issue by WesleyChung** [rmtheis/android-ocr#36]
Your sample worked great for me but does it possible implements android.hardware.camera2 instead of using deprecated old camera api ? If so, how do i start from ? Thank You

**Comment by rmtheis** [comment]
Glad to hear it's working for you. Yes, you could update the code to use the new camera API. Have a look at the code in the `camera` package. Another idea would be to write a similar app that uses the Android Vision API.
