### ISSUE TITLE
Start CaptureActivity from external app

### ISSUE THREAD

**Issue by poseidonjm** [rmtheis/android-ocr#38]
Can I start CaptureActivity from an external app?
Like zxing barcode:
 Intent i = new Intent("com.google.zxing.client.android.SCAN"); 
 startActivityForResult(i, REQ_CODE);

and get the result in  data.getStringExtra("SCAN_RESULT")

**Comment by rmtheis** [comment]
You can do this, but you'd need to make the modifications to this app's code yourself to add an intent filter and handle the intent.

http://developer.android.com/guide/components/intents-filters.html
