### ISSUE TITLE
Is possible if I use two traineddata

### ISSUE THREAD

**Issue by pauljie018** [rmtheis/android-ocr#39]
I created my own traineddata since i Can't combine it to the eng.traineddata. Is it possible for the app to use  use two or more traineddata at the same time.

**Comment by rmtheis** [comment]
Yes. Combine them with a plus sign in `init`: `"eng+hin"` for example.

See https://rmtheis.github.io/tess-two/javadoc/com/googlecode/tesseract/android/TessBaseAPI.html#init(java.lang.String,%20java.lang.String)

**Comment by pauljie018** [comment]
Thanks a lot. This really helped me :)

**Comment by abirbandy** [comment]
where is the init?
