### ISSUE TITLE
Portrait Orientation

### ISSUE THREAD

**Issue by arjunvasan** [rmtheis/android-ocr#4]
Hey rmtheis,

Thanks for your awesome prototype ocr app!  I've been using it to figure out how to get tesseract working on android.  I have a ee signal processing background, and I'm kind of new to android.  

What are the changes needed using your source to switch to portrait mode?  I'm sure you have lots of your own stuff to deal with, but if you have a minute I'd appreciate the help!  How is it that the camera preview appears orthogonal to reality?

Thanks
Arjun

**Comment by akorentlab** [comment]
@slashuer can i please have your code for light? please reply soon
