### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by zouzhenglu** [rmtheis/android-ocr#41]
I download  the source  and  import  to my project ,run,it show me a download  dialog and didn't  run the   
progress  ..Did I  need  to do some  other configuration ??

**Comment by rmtheis** [comment]
Hmm. Does the same thing happen if you download it from Google Play?

**Comment by rmtheis** [comment]
@zouzhenglu, please reopen this issue with more info.

**Comment by zouzhenglu** [comment]
I am in China ,and i do no open the vpn,In my opinion ,if  you need to download sth like  the word  data,May I try to put it into  asset dir by myself .

**Comment by zouzhenglu** [comment]
reopen
