### ISSUE TITLE
How to set up on Eclipse

### ISSUE THREAD

**Issue by JonZarate** [rmtheis/android-ocr#42]
I am not able to get the code running. I import it but it's all a mess since Gradle is used and I can't make it work even though I added the Gradle plugin.

Could you add an explanation on how propperly to add it to Eclipse ? 
I am interested on the API to get the text from an image, so if you could tell me what part does that it would also solve my problem, as I want it for a Java project.

Thank you.

**Comment by rmtheis** [comment]
It's easier to get it working in Android Studio than in Eclipse. For Eclipse, do a `git checkout ebf4b6d` and follow the instructions in the readme. For the OCR API, refer to the tess-two project.
