### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader exception 

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [rmtheis/android-ocr#43]
Hi,
I am trying to run your OCR demo with following steps : 
1. Downloaded ndk 64 bit and saved it in a directory and gave the path in environment variables. 
2. Imported tess-two project in my workspace .
 3. Run ndk-build command which is giving some compiling messages probably compiling the ndk. 4. Now i imported OCRTest demo and used tess-two as library in that demo . When i run the code i got following exception. Log cat details are as follows :

`java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/edu.sfsu.cs.orange.ocr-1/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]] couldn't find "liblept.so"`
It is crashing on this line System.loadLibrary("lept");  
I can find out that  when i run ndk-build, a never ending compiling messages keep on coming and yes one more thing, this particular .so file is in tess-two/libs/armeabi folder. Now can you guide me further what is missing
In my  eclipse project, in libs folder i have only three jar files google-api-translate-java-0.97.jar, jtar-2.1.jar and microsoft-translator-java-api-0.6-mod.jar.
These are few details how i worked so far on ocr, how to take it further from here? Please resolve the issue
Thanks,

**Comment by rmtheis** [comment]
http://stackoverflow.com/questions/36618297/java-lang-unsatisfiedlinkerror-dalvik-system-pathclassloader-error-while-runnin
