### ISSUE TITLE
Where to write the code for opening new activity when we get result after ocr

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [rmtheis/android-ocr#45]
Hi rmtheis,
I have successfully used OCR demo in my app and in this demo , the result is displayed on camera screen itself. My motive is i need to show the result ocr text on another activity.
So where in CaptureActivity.java (or any other class) i should write the code of intent fire since i tried to use two lines of code to open activity many places in the demo but crashed.
Kindly help

**Comment by agnaramonboris** [comment]
Hi !
The result ocr text is show in `boolean handleOcrDecode(OcrResult ocrResult)` method with `ocrResult.getText()`

**Comment by rmtheis** [comment]
It's up to you. agnaramonboris' suggestion is good.
