### ISSUE TITLE
Downloading data for orientation and script detection taking time.

### ISSUE THREAD

**Issue by manpreetsinghsodhi** [rmtheis/android-ocr#48]
I used your demo in my app for ocr. Whenever it runs first time, it downloads some stuff from internet. Can we hardcode it in our app? and if not it is taking time in orientation and script detection. My phone hangs there and i need to run the app again saying "Network issues". But if network issues are there why it is not haulting when ocr downloads english langauge.

Please help me with this issue.

**Comment by rmtheis** [comment]
@manpreetsinghsodhi 1. Yes, try AssetManager. 2. I don't know--sounds particular to your network and not an app issue.
