### ISSUE TITLE
Question about the image taken

### ISSUE THREAD

**Issue by gsiqueira** [rmtheis/android-ocr#49]
Hi,

I am using your project as base for mine, I was trying to access the color of pixels of the image taken but I realized that the image is black and white, and I didn`t find exactly where I can change this option, I mean, intercept the process before the image is converted into black and white. I thought it was under PlanarYUVLuminanceSource.renderCroppedGreyscaleBitmap() but my attempt to change this part didn`t work. Could you help me with this?

Thank you very much.

**Comment by rmtheis** [comment]
Nope, you're on your own for this one!
