### ISSUE TITLE
Detection of shape boundary dynamically like ( (business card) Rectangle , square and Circle) from the camera? 

### ISSUE THREAD

**Issue by mahmooddagga** [rmtheis/android-ocr#50]
I would like to get some help if possible . I'm trying to detect business card   using my Android phone camera but I don't know where to start. so i can Extracting text from image using OCR and process it to read business card..

**Comment by salmangadit** [comment]
I've already implemented something like this on Android. Check project here: https://github.com/salmangadit/scope

**Comment by rmtheis** [comment]
Try OpenCV
