### ISSUE TITLE
Portrait orientation

### ISSUE THREAD

**Issue by aneeshATgithub** [rmtheis/android-ocr#54]
I have had followed this link (http://stackoverflow.com/questions/16252791/zxing-camera-in-portrait-mode-on-android) for achieving portrait orientaion, but when I run on Samsung Galaxy s3 (GT 19300)  the camera is getting blurred. I am attaching the screenshot link also.

https://cloud.githubusercontent.com/assets/12003616/17670274/cff5e170-632e-11e6-903b-9ea8ccfba4cc.png

**Comment by rmtheis** [comment]
This project uses landscape mode, so this issue isn't a problem with this project.
