### ISSUE TITLE
Can not download tessdata

### ISSUE THREAD

**Issue by longnguyencmg** [rmtheis/android-ocr#55]
Please help to check this link to download tessdata. URL not found :(

http://tesseract-ocr.googlecode.com/files/

**Comment by rmtheis** [comment]
This project doesn't use that as a download location, it uses [tesseract-ocr.googlecode.com/files/].(https://github.com/rmtheis/android-ocr/blob/master/OCRTest/src/main/java/edu/sfsu/cs/orange/ocr/CaptureActivity.java#L143)

**Comment by rmtheis** [comment]
Oops, I misread your comment from before. You're saying the trained data download links are broken in the app, right? Do you know of an alternative download location?

**Comment by longnguyencmg** [comment]
Hello, I'm not sure if this https://github.com/tesseract-ocr/tessdata is enough information? 
Currently, I'm looking at your OcrInitAsyncTask.java, you need .traineddata and osd.traineddata. But I just can find .traineddata from the link above.

**Comment by rmtheis** [comment]
Hmm, OK. I think using Firebase or S3 would be better than hotlinking to Github.

Maybe we can include the English/OSD data in the application assets and link to Firebase for the rest.

**Comment by longnguyencmg** [comment]
Actually, I fixed it download .traindeddata from github directly without unzip, etc. But I'm not sure if it's a good solution. I didn't try S3 or Firebase. Waiting for your solution 🎯 . Cheers

**Comment by fdocharles** [comment]
Is any other way to do this.... please its urgent

**Comment by zyxrrr** [comment]
Please help to check this link to download tessdata. URL not found :(

http://tesseract-ocr.googlecode.com/files/

Or help to how to package the appropriate training data files in the app ?

**Comment by tabletguy** [comment]
By checking the base URL of http://tesseract-ocr.googlecode.com it will redirect to a page that says

_tesseract-ocr has Moved!

This project has moved to a new location on the internet. Its new home is at:_ 

https://github.com/tesseract-ocr

Source files in the program could (should) be changed to reflect this, IMO.

**Comment by rmtheis** [comment]
I don't think hotlinking to Github is a good idea. I suggest packaging the data files in the app (like I've done with the English training data) or hosting download yourself using Firebase.
