### ISSUE TITLE
When running

### ISSUE THREAD

**Issue by kevinmel2000** [rmtheis/android-ocr#57]
Error:Execution failed for task ':OCRTest:transformNative_libsWithStripDebugSymbolForDebug'.
> java.lang.NullPointerException (no error message)

**Comment by rmtheis** [comment]
Have you tried the solutions listed here? http://stackoverflow.com/questions/39604417/android-studio-2-2-native-development-migration-issue

**Comment by kevinmel2000** [comment]
thanks man it solve  just change to 2.4 build tool it solve

  compileSdkVersion 24
    buildToolsVersion "24.0.0"
