### ISSUE TITLE
Error:Execution failed for task ':OCRTest:transformNative_libsWithStripDebugSymbolForDebug'. > java.lang.NullPointerException (no error message)

### ISSUE THREAD

**Issue by twlk-jzy** [rmtheis/android-ocr#58]
Error:Execution failed for task ':OCRTest:transformNative_libsWithStripDebugSymbolForDebug'.
> java.lang.NullPointerException (no error message)

**Comment by laveenbalakrishna** [comment]
Same error. How to handle this?

**Comment by rmtheis** [comment]
http://stackoverflow.com/q/39761895/667810

**Comment by rmtheis** [comment]
Restoring the original version (2.1.3) of the Android Gradle plugin fixes this issue. If you skip the prompts to update the Android Gradle plugin then you won't run into this issue in the first place.
