### ISSUE TITLE
How to set up overtime

### ISSUE THREAD

**Issue by UC10D** [rmtheis/android-ocr#61]
How to set up overtime when it  begin to distinguish

**Comment by rmtheis** [comment]
What do you mean by "overtime"?

**Comment by UC10D** [comment]
I have a pic with many text.
When i use "textResult = baseApi.getUTF8Text()"
It will take 30 seconds or more。
I want to set up overtime，if it over and return false。

**Comment by rmtheis** [comment]
Ah, a timeout. You can try setting a timer yourself and using [`stop`](https://github.com/rmtheis/tess-two/blob/647a56bd3e690e889a7d2fd188f9b95be658f395/tess-two/src/com/googlecode/tesseract/android/TessBaseAPI.java#L804). You'll also need update to tess-two 6.2.0, and use getHOCRText in place of getUTF8Text. It may or may not work well depending on what your images look like.
