### ISSUE TITLE
How to add hindi data set manually

### ISSUE THREAD

**Issue by abirbandy** [rmtheis/android-ocr#65]
I downloaded the hindi data set from https://github.com/tesseract-ocr/tessdata/tree/3.04.00 , zipped it and put it under the assets.
What changes do I need to do in the code? and where? so that the app installs hindi along side english when the app starts up.

**Comment by abirbandy** [comment]
figured it out.

**Comment by vinodCoder** [comment]
Can you tell me how to add Hindi?
