### ISSUE TITLE
Gradle build fails 

### ISSUE THREAD

**Issue by pocha** [rmtheis/android-ocr#68]
As mentioned in the README, cloned the project & tried opening it in Android Studio. The gradle build does not complete with error below 

```
Gradle 'android-ocr' project refresh failed
Error:Argument for @NotNull parameter 'key' of com/android/tools/idea/gradle/project/model/ide/android/ModelCache.computeIfAbsent must not be null
```

**Comment by rmtheis** [comment]
Hmm, did you try Android Studio 2.3.3?

**Comment by pocha** [comment]
No. This is Android Studio 3.0. I will try with 2.3 & let you know .

**Comment by rmtheis** [comment]
Considering Android Studio 3.0 is still a "canary" beta version, I'd suggest reporting this issue as an Android Studio bug.
