### ISSUE TITLE
How to resize corners

### ISSUE THREAD

**Issue by nhattv18** [rmtheis/android-ocr#70]
Hi,
I run the project on a 320x480 screen, four white corners too big, how can I resize it? Thank you!

<img width="319" alt="screen shot 2017-07-16 at 5 25 19 pm" src="https://user-images.githubusercontent.com/7285505/28246783-2a758eaa-6a4c-11e7-9b52-a802dc513cd8.png">

**Comment by rmtheis** [comment]
Take a look at [ViewfinderView.java](https://github.com/rmtheis/android-ocr/blob/c7a8bfc7e0f38279f147aa68826c93cfac8fe579/OCRTest/src/main/java/edu/sfsu/cs/orange/ocr/ViewfinderView.java#L360).
