### ISSUE TITLE
Request permission CAMERA,CALL_PHONE... on android 7.0

### ISSUE THREAD

**Issue by nhattv18** [rmtheis/android-ocr#71]
Can you tell me why my other project running on Android 7.0 must ask the user to grant dangerous permissions (like CAMERA, CALL_PHONE...) for the first time, but this project running on Android 7.0 automatically gets all permissions?

**Comment by rmtheis** [comment]
This app has a `targetSdkVersion` value that's less than 23, so runtime permissions aren't required.

It's best for new apps to target a newer version and prompt users for permissions, though -- it's a better experience for users overall.

**Comment by nhattv18** [comment]
Thank you very much, I understand.
