### ISSUE TITLE
[How to] Region of interest to extract specific text 

### ISSUE THREAD

**Issue by kirantpatil** [rmtheis/android-ocr#72]
Hi,

I would like to use region of interest to extract specific text.

I found [ROI](https://github.com/charlesw/tesseract/issues/69) tesseract code which is not android.

What would be the android code to get region of interest ?

Thanks.

**Comment by rmtheis** [comment]
The equivalent method in tess-two is [`setRectangle`](https://rmtheis.github.io/tess-two/javadoc/com/googlecode/tesseract/android/TessBaseAPI.html#setRectangle-android.graphics.Rect-).

**Comment by kirantpatil** [comment]
@rmtheis Thanks.
