### ISSUE TITLE
Sinhala Language Detection 

### ISSUE THREAD

**Issue by ArunaMahaGamage** [rmtheis/android-ocr#77]
Dear Sir,

Thank you for your code ,

I add sin.trinddata to assets folder and changed this variables

/** ISO 639-3 language code indicating the default recognition language. */
  public static final String DEFAULT_SOURCE_LANGUAGE_CODE = "sin";
  
  /** ISO 639-1 language code indicating the default target language for translation. */
  public static final String DEFAULT_TARGET_LANGUAGE_CODE = "si";

But its not working for me.

can you explain what are the appropriate places and  how to change the appropriate places.

Regards ,
Aruna

**Comment by rmtheis** [comment]
You need to describe the problem with more detail than just saying it's "not working." Also, take a look at https://github.com/rmtheis/android-ocr#training-data-for-ocr

**Comment by ArunaMahaGamage** [comment]
Dear sir ,

This is i'm edited you repo. i have added sin.trinddata file and "sin" as a language code.

  https://github.com/ArunaMahaGamage/android-ocr-master

pls tell me what is the place i have done wrongly.

Regards,
Aruna

**Comment by yellowjs0304** [comment]
Hi, Did you succeed in changing the language?
