### ISSUE TITLE
Larger bodies of text cause huge hits to accuracy and processing speed

### ISSUE THREAD

**Issue by Terry-Kusunoki-Martin** [rmtheis/android-ocr#79]
Hi, I've been taking a foray into ocr through this app, and I've noticed that while the accuracy and speed are very good on smaller bodies of text (a paragraph with around 4 sentences takes a few seconds to process), both metrics are significantly worse with larger bodies of text.  The document below took a full 2:34 to process, and the text mostly came out garbled.  I'm not sure if this is a proper issue, but I was wondering what other steps I can take to improve the speed/quality of OCR on larger amounts of text.  Are there extra preprocessing steps I can take aside from thresholding?  Are there parameters that are helpful to set when handling larger documents?  Any advice would be much appreciated.  Thank you very much.

Here is the original image:

<img width="912" alt="screen shot 2018-08-09 at 2 53 08 pm" src="https://user-images.githubusercontent.com/8054076/44058339-dc5a7414-9f1b-11e8-8f7a-dc69c829a2c0.png">

Here is the resultant OCR text:

![screenshot_20180813-170200](https://user-images.githubusercontent.com/8054076/44058898-a53bc8b4-9f1d-11e8-92e4-29b8bb19edcc.jpg)

Here is the marked up bitmap from the OCRResult:

![screenshot_20180813-171412](https://user-images.githubusercontent.com/8054076/44058928-b7edc2f0-9f1d-11e8-8cfa-9cfb42215b50.jpg)

**Comment by rmtheis** [comment]
Yep, you're right. This project just doesn't solve the problems you're describing of slowness and quality issues with a large amount of input text.

You may want to look at Renard Wellnitz' open source [Text Fairy project](https://github.com/renard314/textfairy) that takes a number of steps to solve these problems.
