### ISSUE TITLE
Unable to detect other language

### ISSUE THREAD

**Issue by Ajay-Sunnyhith** [rmtheis/android-ocr#80]
public static final String DEFAULT_SOURCE_LANGUAGE_CODE = "ben";
public static final String DEFAULT_TARGET_LANGUAGE_CODE = "bn";

have done the above changes and added ben.traineddata.zip in assets folder to detect Bengali, but the app is still showing random English characters when tested with Bengali. What else should I do?

**Comment by rmtheis** [comment]
Hmm, not sure. Two ideas off the top of my head are (1) removing the `eng` training data so that you're sure you're only using the Bengali training data and (2) blacklisting the characters that you don't want to see.
