### ISSUE TITLE
Where can i access the Settings?

### ISSUE THREAD

**Issue by klynegame** [rmtheis/android-ocr#82]
Where can i Access the settings of the project i Saw preference.xml but i dont know how can i acccess. 
thanks in advance :)

**Comment by rmtheis** [comment]
It's the old style, where the menu shows up on the black bar at the very bottom of your phone. On some devices you [may have to long-press the recents button](https://android.stackexchange.com/q/141278).

**Comment by klynegame** [comment]
Im using Oppo f1s
